config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'home#index'

  resources :users, only: [:index, :show, :create, :new] do
    collection do
      get '/activate' => 'users#user_activation', as: :activate
    end
  end

  scope :mailgun do
    post '/open' => 'mailgun_webhook#message_open'
    post '/click' => 'mailgun_webhook#message_click'
    post '/bounce' => 'mailgun_webhook#message_bounce'
  end

  require 'sidekiq/web'
  mount Sidekiq::Web => '/admin/sidekiq'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/mailgun_event.rb
# == Schema Information
#
# Table name: mailgun_events
#
#  id         :integer          not null, primary key
#  message_id :integer          not null
#  event      :integer          not null
#  data       :jsonb            default("{}"), not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class MailgunEvent < ApplicationRecord
  belongs_to :message
  validates_presence_of :message, :event

  enum event: {
      opened: 1,
      clicked: 2,
      bounced: 3
  }

end

app/models/message.rb
# == Schema Information
#
# Table name: messages
#
#  id           :integer          not null, primary key
#  user_id      :integer          not null
#  mailgun_id   :citext
#  message_type :integer          default("0"), not null
#  subject      :citext
#  content      :citext
#  opened_at    :datetime
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#

class Message < ApplicationRecord
  belongs_to :user, class_name: 'User'
  has_many :mailgun_events

  validates_presence_of :user, :message_type

  enum message_type: {
      default: 0,
      activation: 1,
      reminder: 2
  }
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id               :integer          not null, primary key
#  name             :citext           not null
#  email            :citext           not null
#  token            :string           not null
#  is_suppressed    :boolean          default("false"), not null
#  invited_at       :datetime         not null
#  reminder_sent_at :datetime
#  activated_at     :datetime
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#

class User < ApplicationRecord
  validates :name, presence: true
  validates :email, uniqueness: true, presence: true, format: /\A[^@\s]+@([^@\s]+\.)+[^@\W]+\z/, case_sensitive: false
  before_create :generate_token
  has_many :messages

  private
    def generate_token
      loop do
        token = SecureRandom.hex(25)
        unless User.where(token: token).first
          self.token = token
          self.invited_at = Time.current
          break
        end
      end
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    
  end
end

app/controllers/mailgun_webhook_controller.rb
class MailgunWebhookController < ApplicationController
  protect_from_forgery with: :null_session

  before_action :validate_request_source

  def message_open
    response = MailgunWebhookService.register_open(
        mailgun_id: open_params['message-id'],
        ip_address: open_params['ip']
    )
    status = response[:error].blank? ? 200 : 422
    render json: response, status: status
  end

  def message_click
    response = MailgunWebhookService.register_event(
        mailgun_id: click_params['message-id'],
        event: click_params['event'],
        ip_address: click_params['ip'],
        email: click_params['recipient']
    )
    status = response[:error].blank? ? 200 : 422
    render json: response, status: status
  end

  def message_bounce
    response = MailgunWebhookService.register_event(
        mailgun_id: bounce_params['Message-Id'].to_s.gsub(/^<|>$/, ''), # Test webhook have different key here
        event: bounce_params['event'],
        data: {
            ip: bounce_params['ip']
        },
        email: click_params['recipient']
    )
    status = response[:error].blank? ? 200 : 422
    render json: response, status: status
  end

  private
  def open_params
    # {
    #     "city"=>"Mountain View",
    #     "domain"=>"ginnielabs.in",
    #     "device-type"=>"desktop",
    #     "client-type"=>"browser",
    #     "h"=>"6973b0199a84ae81eb4ce3bd57b75193",
    #     "region"=>"CA",
    #     "client-name"=>"Firefox",
    #     "user-agent"=>"Mozilla/5.0 (Windows NT 5.1; rv:11.0) Gecko Firefox/11.0 (via ggpht.com GoogleImageProxy)",
    #     "country"=>"US",
    #     "client-os"=>"Windows",
    #     "ip"=>"66.249.84.207",
    #     "message-id"=>"20161214184323.9765.3791.04C62074@ginnielabs.in",
    #     "recipient"=>"chandan.jhun@gmail.com",
    #     "event"=>"opened",
    #     "timestamp"=>"1481741016",
    #     "token"=>"38656dec1c49200c9df449bbf2bfe648fe49a78b2ac95d403e",
    #     "signature"=>"90f658a9cff1a5d6e2c9e86a09eb67b298ef169a3f0ec81eefd8c6671d34bf2a",
    #     "body-plain"=>"",
    #     "controller"=>"mailgun_webhook",
    #     "action"=>"message_open"
    # }
    params.permit(:ip, 'message-id', :recipient, :event, :timestamp, :token, :signature)
  end

  def click_params
    params.permit(:ip, 'message-id', :recipient, :event, :timestamp, :token, :signature)
  end

  def bounce_params
    params.permit(:ip, 'Message-Id', :recipient, :event, :timestamp, :token, :signature)
  end


  def validate_request_source
    data = params[:timestamp].to_s + params[:token].to_s
    key = Rails.application.secrets['mailgun_api_key']
    secure_signature = OpenSSL::HMAC.hexdigest('SHA256', key, data)
    unless secure_signature == params[:signature]
      render json: {
          message: 'Invalid Request'
      }, status: :forbidden and return
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  http_basic_authenticate_with name: 'admin', password: 'password', except: :user_activation

  before_action :set_user, only: [:show]

  # GET /users
  # GET /users.json
  def index
    @users = User.paginate(:page => params[:page])
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)
    respond_to do |format|
      if @user.save
        # Send activation mail if not suppressed
        # Else mark suppressed
        UserActivationJob.perform_later(@user.id)
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def user_activation
    @user = User.find_by(token: params[:token])
    if @user.blank?
      redirect_to :root, alert: 'Invalid Activation token.'
    else
      @user.activated_at = Time.current
      @user.save
      redirect_to :root, notice: 'Successfully activated'
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def user_params
    params.require(:user).permit(:email, :name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/mailgun_webhook_helper.rb
module MailgunWebhookHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<div class="center jumbotron">
  <h1>Thank you for activating your account.</h1>

  <%= link_to 'Admin Portal', users_path, class: "btn btn-lg btn-primary" %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StudySoup</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <div class="container">
    <% flash.each do |key, value| %>
        <%= content_tag(:div, value, class: "alert alert-#{key}")%>
    <% end %>

    <%= yield %>

  </div>
  </body>
</html>

app/views/users/_form.html.erb
<%= form_for(user) do |f| %>
    <% if user.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

          <ul>
            <% user.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
      <%= f.label :name %>
      <%= f.text_field :name %>
    </div>

    <div class="field">
      <%= f.label :email %>
      <%= f.text_field :email %>
    </div>

    <div class="actions">
      <%= f.submit 'Send activation mail', class: "btn btn-primary btn-large"  %>
    </div>
<% end %>

app/views/users/index.html.erb
<h1>Users</h1>

<div class="container">
  <div class="row">
    <div class="table-responsive">
      <div class="col-md-12">
        <div class="panel-body">
          <table class="table table-bordered table-hover table-striped">
            <thead class='row'>
            <tr>
              <th>Name</th>
              <th>Email</th>
              <th>Invited At</th>
              <th>Activated</th>
              <th>Suppressed</th>
              <th>Reminder Sent </th>
              <th>Action</th>
            </tr>
            </thead>

            <tbody>
            <%= will_paginate %>
            <% @users.each do |user| %>
                <tr>
                  <td><%= user.name %></td>
                  <td><%= user.email %></td>
                  <td><%= user.invited_at %></td>
                  <td><%= user.activated_at.present? %></td>
                  <td><%= user.is_suppressed %></td>
                  <td><%= user.reminder_sent_at.present? %></td>
                  <td><%= link_to 'Show', user %></td>
                </tr>
            <% end %>
            <%= will_paginate %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>



<br>

<%= link_to 'New User', new_user_path, class: "btn btn-primary btn-large"  %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<div class="container">
  <div class="row">
    <div class="table-responsive">
      <div class="col-md-12">
        <div class="panel-body">
          <p>
            <strong>Name:</strong>
            <%= @user.name %>
          </p>
          <p>
            <strong>Email:</strong>
            <%= @user.email %>
          </p>
          <table class="table table-bordered table-hover table-striped">
            <thead class='row'>
            <tr>
              <th>Subject</th>
              <th>Message</th>
              <th>Message Type</th>
              <th>Sent At</th>
            </tr>
            </thead>

            <tbody>
            <% @user.messages.each do |message| %>
                <tr>
                  <td><%= message.subject %></td>
                  <td><%= raw(message.content) %></td>
                  <td><%= message.message_type %></td>
                  <td><%= message.created_at %></td>
                </tr>
            <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>

<%= link_to 'Back', users_path %>